# Generated by Django 4.0.4 on 2024-04-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortApp', '0002_projectdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
